/*
 * BNO055.h
 *
 *  Created on: May 21, 2018
 *      Author: pasindu
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef BNO055_definitions_H_
#define BNO055_definitions_H_
#endif /* BNO055_definitions_H_ */

/* Includes ------------------------------------------------------------------*/
#include "main.h"



/********************************************************/
/**    		I2C ADDRESS DEFINITION FOR BNO055           */
/********************************************************/
/* bno055 I2C Address */
#define BNO055_I2C_ADDR1_R              (0x28 << 1) | 0x1
#define BNO055_I2C_ADDR1_W              (0x28 << 1)
#define BNO055_I2C_ADDR2_R              (0x29 << 1) | 0x1
#define BNO055_I2C_ADDR2_W				(0x29 << 1)


/***************************************************/
/**			REGISTER ADDRESS DEFINITION  */
/***************************************************/
/* Page id register definition*/
#define BNO055_PAGE_ID_ADDR				    (0X07)

/* PAGE0 REGISTER DEFINITION START*/
#define BNO055_CHIP_ID_ADDR                 (0x00)
#define BNO055_ACCEL_REV_ID_ADDR			(0x01)
#define BNO055_MAG_REV_ID_ADDR              (0x02)
#define BNO055_GYRO_REV_ID_ADDR             (0x03)
#define BNO055_SW_REV_ID_LSB_ADDR			(0x04)
#define BNO055_SW_REV_ID_MSB_ADDR			(0x05)
#define BNO055_BL_REV_ID_ADDR				(0X06)

/* Accel data register*/
#define BNO055_ACCEL_DATA_X_LSB_ADDR		(0X08)
#define BNO055_ACCEL_DATA_X_MSB_ADDR		(0X09)
#define BNO055_ACCEL_DATA_Y_LSB_ADDR		(0X0A)
#define BNO055_ACCEL_DATA_Y_MSB_ADDR		(0X0B)
#define BNO055_ACCEL_DATA_Z_LSB_ADDR		(0X0C)
#define BNO055_ACCEL_DATA_Z_MSB_ADDR		(0X0D)

/*Mag data register*/
#define BNO055_MAG_DATA_X_LSB_ADDR			(0X0E)
#define BNO055_MAG_DATA_X_MSB_ADDR			(0X0F)
#define BNO055_MAG_DATA_Y_LSB_ADDR			(0X10)
#define BNO055_MAG_DATA_Y_MSB_ADDR			(0X11)
#define BNO055_MAG_DATA_Z_LSB_ADDR			(0X12)
#define BNO055_MAG_DATA_Z_MSB_ADDR			(0X13)

/*Gyro data registers*/
#define BNO055_GYRO_DATA_X_LSB_ADDR			(0X14)
#define BNO055_GYRO_DATA_X_MSB_ADDR			(0X15)
#define BNO055_GYRO_DATA_Y_LSB_ADDR			(0X16)
#define BNO055_GYRO_DATA_Y_MSB_ADDR			(0X17)
#define BNO055_GYRO_DATA_Z_LSB_ADDR			(0X18)
#define BNO055_GYRO_DATA_Z_MSB_ADDR			(0X19)

/*Euler data registers*/
#define BNO055_EULER_H_LSB_ADDR				(0X1A)
#define BNO055_EULER_H_MSB_ADDR				(0X1B)

#define BNO055_EULER_R_LSB_ADDR				(0X1C)
#define BNO055_EULER_R_MSB_ADDR				(0X1D)

#define BNO055_EULER_P_LSB_ADDR				(0X1E)
#define BNO055_EULER_P_MSB_ADDR				(0X1F)

/*Quaternion data registers*/
#define BNO055_QUATERNION_DATA_W_LSB_ADDR	(0X20)
#define BNO055_QUATERNION_DATA_W_MSB_ADDR	(0X21)
#define BNO055_QUATERNION_DATA_X_LSB_ADDR	(0X22)
#define BNO055_QUATERNION_DATA_X_MSB_ADDR	(0X23)
#define BNO055_QUATERNION_DATA_Y_LSB_ADDR	(0X24)
#define BNO055_QUATERNION_DATA_Y_MSB_ADDR	(0X25)
#define BNO055_QUATERNION_DATA_Z_LSB_ADDR	(0X26)
#define BNO055_QUATERNION_DATA_Z_MSB_ADDR	(0X27)

/* Linear acceleration data registers*/
#define BNO055_LINEAR_ACCEL_DATA_X_LSB_ADDR	(0X28)
#define BNO055_LINEAR_ACCEL_DATA_X_MSB_ADDR	(0X29)
#define BNO055_LINEAR_ACCEL_DATA_Y_LSB_ADDR	(0X2A)
#define BNO055_LINEAR_ACCEL_DATA_Y_MSB_ADDR	(0X2B)
#define BNO055_LINEAR_ACCEL_DATA_Z_LSB_ADDR	(0X2C)
#define BNO055_LINEAR_ACCEL_DATA_Z_MSB_ADDR	(0X2D)

/*Gravity data registers*/
#define BNO055_GRAVITY_DATA_X_LSB_ADDR		(0X2E)
#define BNO055_GRAVITY_DATA_X_MSB_ADDR		(0X2F)
#define BNO055_GRAVITY_DATA_Y_LSB_ADDR		(0X30)
#define BNO055_GRAVITY_DATA_Y_MSB_ADDR		(0X31)
#define BNO055_GRAVITY_DATA_Z_LSB_ADDR		(0X32)
#define BNO055_GRAVITY_DATA_Z_MSB_ADDR		(0X33)

/* Temperature data register*/
#define BNO055_TEMP_ADDR					(0X34)

/* Status registers*/
#define BNO055_CALIB_STAT_ADDR				(0X35)
#define BNO055_SELFTEST_RESULT_ADDR			(0X36)
#define BNO055_INTR_STAT_ADDR				(0X37)
#define BNO055_SYS_CLK_STAT_ADDR			(0X38)
#define BNO055_SYS_STAT_ADDR				(0X39)
#define BNO055_SYS_ERR_ADDR					(0X3A)

/* Unit selection register*/
#define BNO055_UNIT_SEL_ADDR				(0X3B)
#define BNO055_DATA_SELECT_ADDR				(0X3C)

/* Mode registers*/
#define BNO055_OPR_MODE_ADDR				(0X3D)
#define BNO055_PWR_MODE_ADDR				(0X3E)

#define BNO055_SYS_TRIGGER_ADDR				(0X3F)
#define BNO055_TEMP_SOURCE_ADDR				(0X40)
/* Axis remap registers*/
#define BNO055_AXIS_MAP_CONFIG_ADDR			(0X41)
#define BNO055_AXIS_MAP_SIGN_ADDR			(0X42)

/* SIC registers*/
#define BNO055_SIC_MATRIX_0_LSB_ADDR		(0X43)
#define BNO055_SIC_MATRIX_0_MSB_ADDR		(0X44)
#define BNO055_SIC_MATRIX_1_LSB_ADDR		(0X45)
#define BNO055_SIC_MATRIX_1_MSB_ADDR		(0X46)
#define BNO055_SIC_MATRIX_2_LSB_ADDR		(0X47)
#define BNO055_SIC_MATRIX_2_MSB_ADDR		(0X48)
#define BNO055_SIC_MATRIX_3_LSB_ADDR		(0X49)
#define BNO055_SIC_MATRIX_3_MSB_ADDR		(0X4A)
#define BNO055_SIC_MATRIX_4_LSB_ADDR		(0X4B)
#define BNO055_SIC_MATRIX_4_MSB_ADDR		(0X4C)
#define BNO055_SIC_MATRIX_5_LSB_ADDR		(0X4D)
#define BNO055_SIC_MATRIX_5_MSB_ADDR		(0X4E)
#define BNO055_SIC_MATRIX_6_LSB_ADDR		(0X4F)
#define BNO055_SIC_MATRIX_6_MSB_ADDR		(0X50)
#define BNO055_SIC_MATRIX_7_LSB_ADDR		(0X51)
#define BNO055_SIC_MATRIX_7_MSB_ADDR		(0X52)
#define BNO055_SIC_MATRIX_8_LSB_ADDR		(0X53)
#define BNO055_SIC_MATRIX_8_MSB_ADDR		(0X54)

/* Accelerometer Offset registers*/
#define BNO055_ACCEL_OFFSET_X_LSB_ADDR			(0X55)
#define BNO055_ACCEL_OFFSET_X_MSB_ADDR			(0X56)
#define BNO055_ACCEL_OFFSET_Y_LSB_ADDR			(0X57)
#define BNO055_ACCEL_OFFSET_Y_MSB_ADDR			(0X58)
#define BNO055_ACCEL_OFFSET_Z_LSB_ADDR			(0X59)
#define BNO055_ACCEL_OFFSET_Z_MSB_ADDR			(0X5A)

/* Magnetometer Offset registers*/
#define BNO055_MAG_OFFSET_X_LSB_ADDR			(0X5B)
#define BNO055_MAG_OFFSET_X_MSB_ADDR			(0X5C)
#define BNO055_MAG_OFFSET_Y_LSB_ADDR			(0X5D)
#define BNO055_MAG_OFFSET_Y_MSB_ADDR			(0X5E)
#define BNO055_MAG_OFFSET_Z_LSB_ADDR			(0X5F)
#define BNO055_MAG_OFFSET_Z_MSB_ADDR			(0X60)

/* Gyroscope Offset registers*/
#define BNO055_GYRO_OFFSET_X_LSB_ADDR			(0X61)
#define BNO055_GYRO_OFFSET_X_MSB_ADDR			(0X62)
#define BNO055_GYRO_OFFSET_Y_LSB_ADDR			(0X63)
#define BNO055_GYRO_OFFSET_Y_MSB_ADDR			(0X64)
#define BNO055_GYRO_OFFSET_Z_LSB_ADDR			(0X65)
#define BNO055_GYRO_OFFSET_Z_MSB_ADDR			(0X66)

/* Radius registers*/
#define	BNO055_ACCEL_RADIUS_LSB_ADDR			(0X67)
#define	BNO055_ACCEL_RADIUS_MSB_ADDR			(0X68)
#define	BNO055_MAG_RADIUS_LSB_ADDR				(0X69)
#define	BNO055_MAG_RADIUS_MSB_ADDR				(0X6A)
/* PAGE0 REGISTERS DEFINITION END*/

/* PAGE1 REGISTERS DEFINITION START*/
/* Configuration registers*/
#define BNO055_ACCEL_CONFIG_ADDR				(0X08)
#define BNO055_MAG_CONFIG_ADDR					(0X09)
#define BNO055_GYRO_CONFIG_ADDR					(0X0A)
#define BNO055_GYRO_MODE_CONFIG_ADDR			(0X0B)
#define BNO055_ACCEL_SLEEP_CONFIG_ADDR			(0X0C)
#define BNO055_GYRO_SLEEP_CONFIG_ADDR			(0X0D)
#define BNO055_MAG_SLEEP_CONFIG_ADDR			(0x0E)

/* Interrupt registers*/
#define BNO055_INT_MASK_ADDR					(0X0F)
#define BNO055_INT_ADDR							(0X10)
#define BNO055_ACCEL_ANY_MOTION_THRES_ADDR		(0X11)
#define BNO055_ACCEL_INTR_SETTINGS_ADDR			(0X12)
#define BNO055_ACCEL_HIGH_G_DURN_ADDR			(0X13)
#define BNO055_ACCEL_HIGH_G_THRES_ADDR			(0X14)
#define BNO055_ACCEL_NO_MOTION_THRES_ADDR		(0X15)
#define BNO055_ACCEL_NO_MOTION_SET_ADDR			(0X16)
#define BNO055_GYRO_INTR_SETING_ADDR			(0X17)
#define BNO055_GYRO_HIGHRATE_X_SET_ADDR			(0X18)
#define BNO055_GYRO_DURN_X_ADDR					(0X19)
#define BNO055_GYRO_HIGHRATE_Y_SET_ADDR			(0X1A)
#define BNO055_GYRO_DURN_Y_ADDR					(0X1B)
#define BNO055_GYRO_HIGHRATE_Z_SET_ADDR			(0X1C)
#define BNO055_GYRO_DURN_Z_ADDR					(0X1D)
#define BNO055_GYRO_ANY_MOTION_THRES_ADDR		(0X1E)
#define BNO055_GYRO_ANY_MOTION_SET_ADDR			(0X1F)



/*********************************************************/
/**\name PAGE0 DATA REGISTERS DEFINITION */
/*********************************************************/
/* Chip ID */
#define BNO055_CHIP_ID_POS             (0)
#define BNO055_CHIP_ID_MSK             (0xFF)
#define BNO055_CHIP_ID_LEN             (8)
#define BNO055_CHIP_ID_REG             BNO055_CHIP_ID_ADDR

/* Accel revision id*/
#define BNO055_ACCEL_REV_ID_POS        (0)
#define BNO055_ACCEL_REV_ID_MSK        (0xFF)
#define BNO055_ACCEL_REV_ID_LEN        (8)
#define BNO055_ACCEL_REV_ID_REG        BNO055_ACCEL_REV_ID_ADDR

/* Mag revision id*/
#define BNO055_MAG_REV_ID_POS          (0)
#define BNO055_MAG_REV_ID_MSK             (0xFF)
#define BNO055_MAG_REV_ID_LEN             (8)
#define BNO055_MAG_REV_ID_REG             BNO055_MAG_REV_ID_ADDR

/* Gyro revision id*/
#define BNO055_GYRO_REV_ID_POS             (0)
#define BNO055_GYRO_REV_ID_MSK             (0xFF)
#define BNO055_GYRO_REV_ID_LEN             (8)
#define BNO055_GYRO_REV_ID_REG             BNO055_GYRO_REV_ID_ADDR

/*Software revision id LSB*/
#define BNO055_SW_REV_ID_LSB_POS             (0)
#define BNO055_SW_REV_ID_LSB_MSK             (0xFF)
#define BNO055_SW_REV_ID_LSB_LEN             (8)
#define BNO055_SW_REV_ID_LSB_REG             BNO055_SW_REV_ID_LSB_ADDR

/*Software revision id MSB*/
#define BNO055_SW_REV_ID_MSB_POS             (0)
#define BNO055_SW_REV_ID_MSB_MSK             (0xFF)
#define BNO055_SW_REV_ID_MSB_LEN             (8)
#define BNO055_SW_REV_ID_MSB_REG             BNO055_SW_REV_ID_MSB_ADDR

/* BOOTLODER revision id*/
#define BNO055_BL_REV_ID_POS             (0)
#define BNO055_BL_REV_ID_MSK             (0xFF)
#define BNO055_BL_REV_ID_LEN             (8)
#define BNO055_BL_REV_ID_REG             BNO055_BL_REV_ID_ADDR

/*Page id*/
#define BNO055_PAGE_ID_POS             (0)
#define BNO055_PAGE_ID_MSK             (0xFF)
#define BNO055_PAGE_ID_LEN             (8)
#define BNO055_PAGE_ID_REG             BNO055_PAGE_ID_ADDR

/* Accel data X-LSB register*/
#define BNO055_ACCEL_DATA_X_LSB_VALUEX_POS             (0)
#define BNO055_ACCEL_DATA_X_LSB_VALUEX_MSK             (0xFF)
#define BNO055_ACCEL_DATA_X_LSB_VALUEX_LEN             (8)
#define BNO055_ACCEL_DATA_X_LSB_VALUEX_REG             \
BNO055_ACCEL_DATA_X_LSB_ADDR

/* Accel data X-MSB register*/
#define BNO055_ACCEL_DATA_X_MSB_VALUEX_POS             (0)
#define BNO055_ACCEL_DATA_X_MSB_VALUEX_MSK             (0xFF)
#define BNO055_ACCEL_DATA_X_MSB_VALUEX_LEN             (8)
#define BNO055_ACCEL_DATA_X_MSB_VALUEX_REG             \
BNO055_ACCEL_DATA_X_MSB_ADDR

/* Accel data Y-LSB register*/
#define BNO055_ACCEL_DATA_Y_LSB_VALUEY_POS             (0)
#define BNO055_ACCEL_DATA_Y_LSB_VALUEY_MSK             (0xFF)
#define BNO055_ACCEL_DATA_Y_LSB_VALUEY_LEN             (8)
#define BNO055_ACCEL_DATA_Y_LSB_VALUEY_REG             \
BNO055_ACCEL_DATA_Y_LSB_ADDR

/* Accel data Y-MSB register*/
#define BNO055_ACCEL_DATA_Y_MSB_VALUEY_POS             (0)
#define BNO055_ACCEL_DATA_Y_MSB_VALUEY_MSK             (0xFF)
#define BNO055_ACCEL_DATA_Y_MSB_VALUEY_LEN             (8)
#define BNO055_ACCEL_DATA_Y_MSB_VALUEY_REG             \
BNO055_ACCEL_DATA_Y_MSB_ADDR

/* Accel data Z-LSB register*/
#define BNO055_ACCEL_DATA_Z_LSB_VALUEZ_POS		(0)
#define BNO055_ACCEL_DATA_Z_LSB_VALUEZ_MSK		(0xFF)
#define BNO055_ACCEL_DATA_Z_LSB_VALUEZ_LEN		(8)
#define BNO055_ACCEL_DATA_Z_LSB_VALUEZ_REG     \
BNO055_ACCEL_DATA_Z_LSB_ADDR

/* Accel data Z-MSB register*/
#define BNO055_ACCEL_DATA_Z_MSB_VALUEZ_POS		(0)
#define BNO055_ACCEL_DATA_Z_MSB_VALUEZ_MSK		(0xFF)
#define BNO055_ACCEL_DATA_Z_MSB_VALUEZ_LEN		(8)
#define BNO055_ACCEL_DATA_Z_MSB_VALUEZ_REG     \
BNO055_ACCEL_DATA_Z_MSB_ADDR

/* Mag data X-LSB register*/
#define BNO055_MAG_DATA_X_LSB_VALUEX_POS             (0)
#define BNO055_MAG_DATA_X_LSB_VALUEX_MSK             (0xFF)
#define BNO055_MAG_DATA_X_LSB_VALUEX_LEN             (8)
#define BNO055_MAG_DATA_X_LSB_VALUEX_REG             \
BNO055_MAG_DATA_X_LSB_ADDR

/* Mag data X-MSB register*/
#define BNO055_MAG_DATA_X_MSB_VALUEX_POS             (0)
#define BNO055_MAG_DATA_X_MSB_VALUEX_MSK             (0xFF)
#define BNO055_MAG_DATA_X_MSB_VALUEX_LEN             (8)
#define BNO055_MAG_DATA_X_MSB_VALUEX_REG             BNO055_MAG_DATA_X_MSB_ADDR

/* Mag data Y-LSB register*/
#define BNO055_MAG_DATA_Y_LSB_VALUEY_POS             (0)
#define BNO055_MAG_DATA_Y_LSB_VALUEY_MSK             (0xFF)
#define BNO055_MAG_DATA_Y_LSB_VALUEY_LEN             (8)
#define BNO055_MAG_DATA_Y_LSB_VALUEY_REG             BNO055_MAG_DATA_Y_LSB_ADDR

/* Mag data Y-MSB register*/
#define BNO055_MAG_DATA_Y_MSB_VALUEY_POS             (0)
#define BNO055_MAG_DATA_Y_MSB_VALUEY_MSK             (0xFF)
#define BNO055_MAG_DATA_Y_MSB_VALUEY_LEN             (8)
#define BNO055_MAG_DATA_Y_MSB_VALUEY_REG             BNO055_MAG_DATA_Y_MSB_ADDR

/* Mag data Z-LSB register*/
#define BNO055_MAG_DATA_Z_LSB_VALUEZ_POS             (0)
#define BNO055_MAG_DATA_Z_LSB_VALUEZ_MSK             (0xFF)
#define BNO055_MAG_DATA_Z_LSB_VALUEZ_LEN             (8)
#define BNO055_MAG_DATA_Z_LSB_VALUEZ_REG             BNO055_MAG_DATA_Z_LSB_ADDR

/* Mag data Z-MSB register*/
#define BNO055_MAG_DATA_Z_MSB_VALUEZ_POS             (0)
#define BNO055_MAG_DATA_Z_MSB_VALUEZ_MSK             (0xFF)
#define BNO055_MAG_DATA_Z_MSB_VALUEZ_LEN             (8)
#define BNO055_MAG_DATA_Z_MSB_VALUEZ_REG             BNO055_MAG_DATA_Z_MSB_ADDR

/* Gyro data X-LSB register*/
#define BNO055_GYRO_DATA_X_LSB_VALUEX_POS	(0)
#define BNO055_GYRO_DATA_X_LSB_VALUEX_MSK	(0xFF)
#define BNO055_GYRO_DATA_X_LSB_VALUEX_LEN	(8)
#define BNO055_GYRO_DATA_X_LSB_VALUEX_REG	BNO055_GYRO_DATA_X_LSB_ADDR

/* Gyro data X-MSB register*/
#define BNO055_GYRO_DATA_X_MSB_VALUEX_POS	(0)
#define BNO055_GYRO_DATA_X_MSB_VALUEX_MSK	(0xFF)
#define BNO055_GYRO_DATA_X_MSB_VALUEX_LEN	(8)
#define BNO055_GYRO_DATA_X_MSB_VALUEX_REG	BNO055_GYRO_DATA_X_MSB_ADDR

/* Gyro data Y-LSB register*/
#define BNO055_GYRO_DATA_Y_LSB_VALUEY_POS	(0)
#define BNO055_GYRO_DATA_Y_LSB_VALUEY_MSK	(0xFF)
#define BNO055_GYRO_DATA_Y_LSB_VALUEY_LEN	(8)
#define BNO055_GYRO_DATA_Y_LSB_VALUEY_REG	BNO055_GYRO_DATA_Y_LSB_ADDR

/* Gyro data Y-MSB register*/
#define BNO055_GYRO_DATA_Y_MSB_VALUEY_POS	(0)
#define BNO055_GYRO_DATA_Y_MSB_VALUEY_MSK	(0xFF)
#define BNO055_GYRO_DATA_Y_MSB_VALUEY_LEN	(8)
#define BNO055_GYRO_DATA_Y_MSB_VALUEY_REG	BNO055_GYRO_DATA_Y_MSB_ADDR

/* Gyro data Z-LSB register*/
#define BNO055_GYRO_DATA_Z_LSB_VALUEZ_POS	(0)
#define BNO055_GYRO_DATA_Z_LSB_VALUEZ_MSK	(0xFF)
#define BNO055_GYRO_DATA_Z_LSB_VALUEZ_LEN	(8)
#define BNO055_GYRO_DATA_Z_LSB_VALUEZ_REG	BNO055_GYRO_DATA_Z_LSB_ADDR

/* Gyro data Z-MSB register*/
#define BNO055_GYRO_DATA_Z_MSB_VALUEZ_POS	(0)
#define BNO055_GYRO_DATA_Z_MSB_VALUEZ_MSK	(0xFF)
#define BNO055_GYRO_DATA_Z_MSB_VALUEZ_LEN	(8)
#define BNO055_GYRO_DATA_Z_MSB_VALUEZ_REG	BNO055_GYRO_DATA_Z_MSB_ADDR

/* Euler data HEADING-LSB register*/
#define BNO055_EULER_H_LSB_VALUEH_POS   (0)
#define BNO055_EULER_H_LSB_VALUEH_MSK   (0xFF)
#define BNO055_EULER_H_LSB_VALUEH_LEN   (8)
#define BNO055_EULER_H_LSB_VALUEH_REG  BNO055_EULER_H_LSB_ADDR

/* Euler data HEADING-MSB register*/
#define BNO055_EULER_H_MSB_VALUEH_POS  (0)
#define BNO055_EULER_H_MSB_VALUEH_MSK  (0xFF)
#define BNO055_EULER_H_MSB_VALUEH_LEN  (8)
#define BNO055_EULER_H_MSB_VALUEH_REG  BNO055_EULER_H_MSB_ADDR

/* Euler data ROLL-LSB register*/
#define BNO055_EULER_R_LSB_VALUER_POS  (0)
#define BNO055_EULER_R_LSB_VALUER_MSK  (0xFF)
#define BNO055_EULER_R_LSB_VALUER_LEN  (8)
#define BNO055_EULER_R_LSB_VALUER_REG  BNO055_EULER_R_LSB_ADDR

/* Euler data ROLL-MSB register*/
#define BNO055_EULER_R_MSB_VALUER_POS  (0)
#define BNO055_EULER_R_MSB_VALUER_MSK  (0xFF)
#define BNO055_EULER_R_MSB_VALUER_LEN  (8)
#define BNO055_EULER_R_MSB_VALUER_REG  BNO055_EULER_R_MSB_ADDR

/* Euler data PITCH-LSB register*/
#define BNO055_EULER_P_LSB_VALUEP_POS  (0)
#define BNO055_EULER_P_LSB_VALUEP_MSK  (0xFF)
#define BNO055_EULER_P_LSB_VALUEP_LEN  (8)
#define BNO055_EULER_P_LSB_VALUEP_REG  BNO055_EULER_P_LSB_ADDR

/* Euler data HEADING-MSB register*/
#define BNO055_EULER_P_MSB_VALUEP_POS  (0)
#define BNO055_EULER_P_MSB_VALUEP_MSK  (0xFF)
#define BNO055_EULER_P_MSB_VALUEP_LEN  (8)
#define BNO055_EULER_P_MSB_VALUEP_REG  BNO055_EULER_P_MSB_ADDR

/* Quaternion data W-LSB register*/
#define BNO055_QUATERNION_DATA_W_LSB_VALUEW_POS  (0)
#define BNO055_QUATERNION_DATA_W_LSB_VALUEW_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_W_LSB_VALUEW_LEN  (8)
#define BNO055_QUATERNION_DATA_W_LSB_VALUEW_REG  \
BNO055_QUATERNION_DATA_W_LSB_ADDR

/* Quaternion data W-MSB register*/
#define BNO055_QUATERNION_DATA_W_MSB_VALUEW_POS  (0)
#define BNO055_QUATERNION_DATA_W_MSB_VALUEW_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_W_MSB_VALUEW_LEN  (8)
#define BNO055_QUATERNION_DATA_W_MSB_VALUEW_REG  \
BNO055_QUATERNION_DATA_W_MSB_ADDR

/* Quaternion data X-LSB register*/
#define BNO055_QUATERNION_DATA_X_LSB_VALUEX_POS  (0)
#define BNO055_QUATERNION_DATA_X_LSB_VALUEX_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_X_LSB_VALUEX_LEN  (8)
#define BNO055_QUATERNION_DATA_X_LSB_VALUEX_REG  \
BNO055_QUATERNION_DATA_X_LSB_ADDR

/* Quaternion data X-MSB register*/
#define BNO055_QUATERNION_DATA_X_MSB_VALUEX_POS  (0)
#define BNO055_QUATERNION_DATA_X_MSB_VALUEX_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_X_MSB_VALUEX_LEN  (8)
#define BNO055_QUATERNION_DATA_X_MSB_VALUEX_REG \
BNO055_QUATERNION_DATA_X_MSB_ADDR

/* Quaternion data Y-LSB register*/
#define BNO055_QUATERNION_DATA_Y_LSB_VALUEY_POS  (0)
#define BNO055_QUATERNION_DATA_Y_LSB_VALUEY_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_Y_LSB_VALUEY_LEN  (8)
#define BNO055_QUATERNION_DATA_Y_LSB_VALUEY_REG \
BNO055_QUATERNION_DATA_Y_LSB_ADDR

/* Quaternion data Y-MSB register*/
#define BNO055_QUATERNION_DATA_Y_MSB_VALUEY_POS  (0)
#define BNO055_QUATERNION_DATA_Y_MSB_VALUEY_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_Y_MSB_VALUEY_LEN  (8)
#define BNO055_QUATERNION_DATA_Y_MSB_VALUEY_REG  \
BNO055_QUATERNION_DATA_Y_MSB_ADDR

/* Quaternion data Z-LSB register*/
#define BNO055_QUATERNION_DATA_Z_LSB_VALUEZ_POS  (0)
#define BNO055_QUATERNION_DATA_Z_LSB_VALUEZ_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_Z_LSB_VALUEZ_LEN  (8)
#define BNO055_QUATERNION_DATA_Z_LSB_VALUEZ_REG \
BNO055_QUATERNION_DATA_Z_LSB_ADDR

/* Quaternion data Z-MSB register*/
#define BNO055_QUATERNION_DATA_Z_MSB_VALUEZ_POS  (0)
#define BNO055_QUATERNION_DATA_Z_MSB_VALUEZ_MSK  (0xFF)
#define BNO055_QUATERNION_DATA_Z_MSB_VALUEZ_LEN  (8)
#define BNO055_QUATERNION_DATA_Z_MSB_VALUEZ_REG  \
BNO055_QUATERNION_DATA_Z_MSB_ADDR

/* Linear acceleration data X-LSB register*/
#define BNO055_LINEAR_ACCEL_DATA_X_LSB_VALUEX_POS  (0)
#define BNO055_LINEAR_ACCEL_DATA_X_LSB_VALUEX_MSK  (0xFF)
#define BNO055_LINEAR_ACCEL_DATA_X_LSB_VALUEX_LEN  (8)
#define BNO055_LINEAR_ACCEL_DATA_X_LSB_VALUEX_REG  \
BNO055_LINEAR_ACCEL_DATA_X_LSB_ADDR

/* Linear acceleration data X-MSB register*/
#define BNO055_LINEAR_ACCEL_DATA_X_MSB_VALUEX_POS  (0)
#define BNO055_LINEAR_ACCEL_DATA_X_MSB_VALUEX_MSK  (0xFF)
#define BNO055_LINEAR_ACCEL_DATA_X_MSB_VALUEX_LEN  (8)
#define BNO055_LINEAR_ACCEL_DATA_X_MSB_VALUEX_REG  \
BNO055_LINEAR_ACCEL_DATA_X_MSB_ADDR

/* Linear acceleration data Y-LSB register*/
#define BNO055_LINEAR_ACCEL_DATA_Y_LSB_VALUEY_POS  (0)
#define BNO055_LINEAR_ACCEL_DATA_Y_LSB_VALUEY_MSK  (0xFF)
#define BNO055_LINEAR_ACCEL_DATA_Y_LSB_VALUEY_LEN  (8)
#define BNO055_LINEAR_ACCEL_DATA_Y_LSB_VALUEY_REG  \
BNO055_LINEAR_ACCEL_DATA_Y_LSB_ADDR

/* Linear acceleration data Y-MSB register*/
#define BNO055_LINEAR_ACCEL_DATA_Y_MSB_VALUEY_POS  (0)
#define BNO055_LINEAR_ACCEL_DATA_Y_MSB_VALUEY_MSK  (0xFF)
#define BNO055_LINEAR_ACCEL_DATA_Y_MSB_VALUEY_LEN  (8)
#define BNO055_LINEAR_ACCEL_DATA_Y_MSB_VALUEY_REG  \
BNO055_LINEAR_ACCEL_DATA_Y_MSB_ADDR

/* Linear acceleration data Z-LSB register*/
#define BNO055_LINEAR_ACCEL_DATA_Z_LSB_VALUEZ_POS  (0)
#define BNO055_LINEAR_ACCEL_DATA_Z_LSB_VALUEZ_MSK  (0xFF)
#define BNO055_LINEAR_ACCEL_DATA_Z_LSB_VALUEZ_LEN  (8)
#define BNO055_LINEAR_ACCEL_DATA_Z_LSB_VALUEZ_REG \
BNO055_LINEAR_ACCEL_DATA_Z_LSB_ADDR

/* Linear acceleration data Z-MSB register*/
#define BNO055_LINEAR_ACCEL_DATA_Z_MSB_VALUEZ_POS  (0)
#define BNO055_LINEAR_ACCEL_DATA_Z_MSB_VALUEZ_MSK  (0xFF)
#define BNO055_LINEAR_ACCEL_DATA_Z_MSB_VALUEZ_LEN  (8)
#define BNO055_LINEAR_ACCEL_DATA_Z_MSB_VALUEZ_REG  \
BNO055_LINEAR_ACCEL_DATA_Z_MSB_ADDR

/* Gravity data X-LSB register*/
#define BNO055_GRAVITY_DATA_X_LSB_VALUEX_POS  (0)
#define BNO055_GRAVITY_DATA_X_LSB_VALUEX_MSK  (0xFF)
#define BNO055_GRAVITY_DATA_X_LSB_VALUEX_LEN  (8)
#define BNO055_GRAVITY_DATA_X_LSB_VALUEX_REG  \
BNO055_GRAVITY_DATA_X_LSB_ADDR

/* Gravity data X-MSB register*/
#define BNO055_GRAVITY_DATA_X_MSB_VALUEX_POS  (0)
#define BNO055_GRAVITY_DATA_X_MSB_VALUEX_MSK  (0xFF)
#define BNO055_GRAVITY_DATA_X_MSB_VALUEX_LEN  (8)
#define BNO055_GRAVITY_DATA_X_MSB_VALUEX_REG  \
BNO055_GRAVITY_DATA_X_MSB_ADDR

/* Gravity data Y-LSB register*/
#define BNO055_GRAVITY_DATA_Y_LSB_VALUEY_POS  (0)
#define BNO055_GRAVITY_DATA_Y_LSB_VALUEY_MSK  (0xFF)
#define BNO055_GRAVITY_DATA_Y_LSB_VALUEY_LEN  (8)
#define BNO055_GRAVITY_DATA_Y_LSB_VALUEY_REG  \
BNO055_GRAVITY_DATA_Y_LSB_ADDR

/* Gravity data Y-MSB register*/
#define BNO055_GRAVITY_DATA_Y_MSB_VALUEY_POS  (0)
#define BNO055_GRAVITY_DATA_Y_MSB_VALUEY_MSK  (0xFF)
#define BNO055_GRAVITY_DATA_Y_MSB_VALUEY_LEN  (8)
#define BNO055_GRAVITY_DATA_Y_MSB_VALUEY_REG  \
BNO055_GRAVITY_DATA_Y_MSB_ADDR

/* Gravity data Z-LSB register*/
#define BNO055_GRAVITY_DATA_Z_LSB_VALUEZ_POS  (0)
#define BNO055_GRAVITY_DATA_Z_LSB_VALUEZ_MSK  (0xFF)
#define BNO055_GRAVITY_DATA_Z_LSB_VALUEZ_LEN  (8)
#define BNO055_GRAVITY_DATA_Z_LSB_VALUEZ_REG  \
BNO055_GRAVITY_DATA_Z_LSB_ADDR

/* Gravity data Z-MSB register*/
#define BNO055_GRAVITY_DATA_Z_MSB_VALUEZ_POS  (0)
#define BNO055_GRAVITY_DATA_Z_MSB_VALUEZ_MSK  (0xFF)
#define BNO055_GRAVITY_DATA_Z_MSB_VALUEZ_LEN  (8)
#define BNO055_GRAVITY_DATA_Z_MSB_VALUEZ_REG  \
BNO055_GRAVITY_DATA_Z_MSB_ADDR

/* Temperature register*/
#define BNO055_TEMP_POS             (0)
#define BNO055_TEMP_MSK             (0xFF)
#define BNO055_TEMP_LEN             (8)
#define BNO055_TEMP_REG             BNO055_TEMP_ADDR

/*Mag_Calib status register*/
#define BNO055_MAG_CALIB_STAT_POS             (0)
#define BNO055_MAG_CALIB_STAT_MSK             (0X03)
#define BNO055_MAG_CALIB_STAT_LEN             (2)
#define BNO055_MAG_CALIB_STAT_REG             BNO055_CALIB_STAT_ADDR

/*Acc_Calib status register*/
#define BNO055_ACCEL_CALIB_STAT_POS             (2)
#define BNO055_ACCEL_CALIB_STAT_MSK             (0X0C)
#define BNO055_ACCEL_CALIB_STAT_LEN             (2)
#define BNO055_ACCEL_CALIB_STAT_REG             BNO055_CALIB_STAT_ADDR

/*Gyro_Calib status register*/
#define BNO055_GYRO_CALIB_STAT_POS             (4)
#define BNO055_GYRO_CALIB_STAT_MSK             (0X30)
#define BNO055_GYRO_CALIB_STAT_LEN             (2)
#define BNO055_GYRO_CALIB_STAT_REG             BNO055_CALIB_STAT_ADDR

/*Sys_Calib status register*/
#define BNO055_SYS_CALIB_STAT_POS             (6)
#define BNO055_SYS_CALIB_STAT_MSK             (0XC0)
#define BNO055_SYS_CALIB_STAT_LEN             (2)
#define BNO055_SYS_CALIB_STAT_REG             BNO055_CALIB_STAT_ADDR

/*ST_ACCEL register*/
#define BNO055_SELFTEST_ACCEL_POS             (0)
#define BNO055_SELFTEST_ACCEL_MSK             (0X01)
#define BNO055_SELFTEST_ACCEL_LEN             (1)
#define BNO055_SELFTEST_ACCEL_REG             BNO055_SELFTEST_RESULT_ADDR

/*ST_MAG register*/
#define BNO055_SELFTEST_MAG_POS             (1)
#define BNO055_SELFTEST_MAG_MSK             (0X02)
#define BNO055_SELFTEST_MAG_LEN             (1)
#define BNO055_SELFTEST_MAG_REG             BNO055_SELFTEST_RESULT_ADDR

/*ST_GYRO register*/
#define BNO055_SELFTEST_GYRO_POS             (2)
#define BNO055_SELFTEST_GYRO_MSK             (0X04)
#define BNO055_SELFTEST_GYRO_LEN             (1)
#define BNO055_SELFTEST_GYRO_REG             BNO055_SELFTEST_RESULT_ADDR

/*ST_MCU register*/
#define BNO055_SELFTEST_MCU_POS             (3)
#define BNO055_SELFTEST_MCU_MSK             (0X08)
#define BNO055_SELFTEST_MCU_LEN             (1)
#define BNO055_SELFTEST_MCU_REG             BNO055_SELFTEST_RESULT_ADDR

/*Interrupt status registers*/
#define BNO055_INTR_STAT_GYRO_ANY_MOTION_POS		(2)
#define BNO055_INTR_STAT_GYRO_ANY_MOTION_MSK		(0X04)
#define BNO055_INTR_STAT_GYRO_ANY_MOTION_LEN		(1)
#define BNO055_INTR_STAT_GYRO_ANY_MOTION_REG		BNO055_INTR_STAT_ADDR

#define BNO055_INTR_STAT_GYRO_HIGHRATE_POS		(3)
#define BNO055_INTR_STAT_GYRO_HIGHRATE_MSK		(0X08)
#define BNO055_INTR_STAT_GYRO_HIGHRATE_LEN		(1)
#define BNO055_INTR_STAT_GYRO_HIGHRATE_REG		BNO055_INTR_STAT_ADDR

#define BNO055_INTR_STAT_ACCEL_HIGH_G_POS		(5)
#define BNO055_INTR_STAT_ACCEL_HIGH_G_MSK		(0X20)
#define BNO055_INTR_STAT_ACCEL_HIGH_G_LEN		(1)
#define BNO055_INTR_STAT_ACCEL_HIGH_G_REG		BNO055_INTR_STAT_ADDR

#define BNO055_INTR_STAT_ACCEL_ANY_MOTION_POS		(6)
#define BNO055_INTR_STAT_ACCEL_ANY_MOTION_MSK		(0X40)
#define BNO055_INTR_STAT_ACCEL_ANY_MOTION_LEN		(1)
#define BNO055_INTR_STAT_ACCEL_ANY_MOTION_REG		BNO055_INTR_STAT_ADDR

#define BNO055_INTR_STAT_ACCEL_NO_MOTION_POS		(7)
#define BNO055_INTR_STAT_ACCEL_NO_MOTION_MSK		(0X80)
#define BNO055_INTR_STAT_ACCEL_NO_MOTION_LEN		(1)
#define BNO055_INTR_STAT_ACCEL_NO_MOTION_REG		BNO055_INTR_STAT_ADDR

/* system clock status register*/
#define BNO055_SYS_MAIN_CLK_POS		(0)
#define BNO055_SYS_MAIN_CLK_MSK		(0X10)
#define BNO055_SYS_MAIN_CLK_LEN		(1)
#define BNO055_SYS_MAIN_CLK_REG		BNO055_SYS_CLK_STAT_ADDR

/* System registers*/
#define BNO055_SYS_STAT_CODE_POS		(0)
#define BNO055_SYS_STAT_CODE_MSK		(0XFF)
#define BNO055_SYS_STAT_CODE_LEN		(8)
#define BNO055_SYS_STAT_CODE_REG		BNO055_SYS_STAT_ADDR

#define BNO055_SYS_ERROR_CODE_POS			(0)
#define BNO055_SYS_ERROR_CODE_MSK			(0XFF)
#define BNO055_SYS_ERROR_CODE_LEN			(8)
#define BNO055_SYS_ERROR_CODE_REG			BNO055_SYS_ERR_ADDR

/* Accel_Unit register*/
#define BNO055_ACCEL_UNIT_POS             (0)
#define BNO055_ACCEL_UNIT_MSK             (0X01)
#define BNO055_ACCEL_UNIT_LEN             (1)
#define BNO055_ACCEL_UNIT_REG             BNO055_UNIT_SEL_ADDR

/* Gyro_Unit register*/
#define BNO055_GYRO_UNIT_POS             (1)
#define BNO055_GYRO_UNIT_MSK             (0X02)
#define BNO055_GYRO_UNIT_LEN             (1)
#define BNO055_GYRO_UNIT_REG             BNO055_UNIT_SEL_ADDR

/* Euler_Unit register*/
#define BNO055_EULER_UNIT_POS             (2)
#define BNO055_EULER_UNIT_MSK             (0X04)
#define BNO055_EULER_UNIT_LEN             (1)
#define BNO055_EULER_UNIT_REG             BNO055_UNIT_SEL_ADDR

/* Tilt_Unit register*/
#define BNO055_TILT_UNIT_POS             (3)
#define BNO055_TILT_UNIT_MSK             (0X08)
#define BNO055_TILT_UNIT_LEN             (1)
#define BNO055_TILT_UNIT_REG             BNO055_UNIT_SEL_ADDR

/* Temperature_Unit register*/
#define BNO055_TEMP_UNIT_POS             (4)
#define BNO055_TEMP_UNIT_MSK             (0X10)
#define BNO055_TEMP_UNIT_LEN             (1)
#define BNO055_TEMP_UNIT_REG             BNO055_UNIT_SEL_ADDR

/* ORI android-windows register*/
#define BNO055_DATA_OUTPUT_FORMAT_POS             (7)
#define BNO055_DATA_OUTPUT_FORMAT_MSK             (0X80)
#define BNO055_DATA_OUTPUT_FORMAT_LEN             (1)
#define BNO055_DATA_OUTPUT_FORMAT_REG             BNO055_UNIT_SEL_ADDR
/*Operation Mode data register*/
#define BNO055_OPERATION_MODE_POS			(0)
#define BNO055_OPERATION_MODE_MSK			(0X0F)
#define BNO055_OPERATION_MODE_LEN			(4)
#define BNO055_OPERATION_MODE_REG			BNO055_OPR_MODE_ADDR
/* Power Mode register*/
#define BNO055_POWER_MODE_POS             (0)
#define BNO055_POWER_MODE_MSK             (0X03)
#define BNO055_POWER_MODE_LEN             (2)
#define BNO055_POWER_MODE_REG             BNO055_PWR_MODE_ADDR

/*Self Test register*/
#define BNO055_SELFTEST_POS			(0)
#define BNO055_SELFTEST_MSK			(0X01)
#define BNO055_SELFTEST_LEN			(1)
#define BNO055_SELFTEST_REG			BNO055_SYS_TRIGGER_ADDR

/* RST_SYS register*/
#define BNO055_SYS_RST_POS             (5)
#define BNO055_SYS_RST_MSK             (0X20)
#define BNO055_SYS_RST_LEN             (1)
#define BNO055_SYS_RST_REG             BNO055_SYS_TRIGGER_ADDR

/* RST_INT register*/
#define BNO055_INTR_RST_POS             (6)
#define BNO055_INTR_RST_MSK             (0X40)
#define BNO055_INTR_RST_LEN             (1)
#define BNO055_INTR_RST_REG             BNO055_SYS_TRIGGER_ADDR

/* CLK_SRC register*/
#define BNO055_CLK_SRC_POS             (7)
#define BNO055_CLK_SRC_MSK             (0X80)
#define BNO055_CLK_SRC_LEN             (1)
#define BNO055_CLK_SRC_REG             BNO055_SYS_TRIGGER_ADDR

/* Temp source register*/
#define BNO055_TEMP_SOURCE_POS		(0)
#define BNO055_TEMP_SOURCE_MSK		(0X03)
#define BNO055_TEMP_SOURCE_LEN		(2)
#define BNO055_TEMP_SOURCE_REG		BNO055_TEMP_SOURCE_ADDR

/* Axis remap value register*/
#define BNO055_REMAP_AXIS_VALUE_POS		(0)
#define BNO055_REMAP_AXIS_VALUE_MSK		(0X3F)
#define BNO055_REMAP_AXIS_VALUE_LEN		(6)
#define BNO055_REMAP_AXIS_VALUE_REG		BNO055_AXIS_MAP_CONFIG_ADDR

/* Axis sign value register*/
#define BNO055_REMAP_Z_SIGN_POS		(0)
#define BNO055_REMAP_Z_SIGN_MSK		(0X01)
#define BNO055_REMAP_Z_SIGN_LEN		(1)
#define BNO055_REMAP_Z_SIGN_REG		BNO055_AXIS_MAP_SIGN_ADDR

#define BNO055_REMAP_Y_SIGN_POS		(1)
#define BNO055_REMAP_Y_SIGN_MSK		(0X02)
#define BNO055_REMAP_Y_SIGN_LEN		(1)
#define BNO055_REMAP_Y_SIGN_REG		BNO055_AXIS_MAP_SIGN_ADDR

#define BNO055_REMAP_X_SIGN_POS		(2)
#define BNO055_REMAP_X_SIGN_MSK		(0X04)
#define BNO055_REMAP_X_SIGN_LEN		(1)
#define BNO055_REMAP_X_SIGN_REG		BNO055_AXIS_MAP_SIGN_ADDR

/* Soft Iron Calibration matrix register*/
#define BNO055_SIC_MATRIX_0_LSB_POS		(0)
#define BNO055_SIC_MATRIX_0_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_0_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_0_LSB_REG		BNO055_SIC_MATRIX_0_LSB_ADDR

#define BNO055_SIC_MATRIX_0_MSB_POS		(0)
#define BNO055_SIC_MATRIX_0_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_0_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_0_MSB_REG		BNO055_SIC_MATRIX_0_MSB_ADDR

#define BNO055_SIC_MATRIX_1_LSB_POS		(0)
#define BNO055_SIC_MATRIX_1_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_1_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_1_LSB_REG		BNO055_SIC_MATRIX_1_LSB_ADDR

#define BNO055_SIC_MATRIX_1_MSB_POS		(0)
#define BNO055_SIC_MATRIX_1_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_1_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_1_MSB_REG		BNO055_SIC_MATRIX_1_MSB_ADDR

#define BNO055_SIC_MATRIX_2_LSB_POS		(0)
#define BNO055_SIC_MATRIX_2_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_2_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_2_LSB_REG		BNO055_SIC_MATRIX_2_LSB_ADDR

#define BNO055_SIC_MATRIX_2_MSB_POS		(0)
#define BNO055_SIC_MATRIX_2_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_2_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_2_MSB_REG		BNO055_SIC_MATRIX_2_MSB_ADDR

#define BNO055_SIC_MATRIX_3_LSB_POS		(0)
#define BNO055_SIC_MATRIX_3_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_3_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_3_LSB_REG		BNO055_SIC_MATRIX_3_LSB_ADDR

#define BNO055_SIC_MATRIX_3_MSB_POS		(0)
#define BNO055_SIC_MATRIX_3_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_3_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_3_MSB_REG		BNO055_SIC_MATRIX_3_MSB_ADDR

#define BNO055_SIC_MATRIX_4_LSB_POS		(0)
#define BNO055_SIC_MATRIX_4_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_4_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_4_LSB_REG		BNO055_SIC_MATRIX_4_LSB_ADDR

#define BNO055_SIC_MATRIX_4_MSB_POS		(0)
#define BNO055_SIC_MATRIX_4_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_4_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_4_MSB_REG		BNO055_SIC_MATRIX_4_MSB_ADDR

#define BNO055_SIC_MATRIX_5_LSB_POS		(0)
#define BNO055_SIC_MATRIX_5_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_5_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_5_LSB_REG		BNO055_SIC_MATRIX_5_LSB_ADDR

#define BNO055_SIC_MATRIX_5_MSB_POS		(0)
#define BNO055_SIC_MATRIX_5_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_5_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_5_MSB_REG		BNO055_SIC_MATRIX_5_MSB_ADDR

#define BNO055_SIC_MATRIX_6_LSB_POS		(0)
#define BNO055_SIC_MATRIX_6_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_6_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_6_LSB_REG		BNO055_SIC_MATRIX_6_LSB_ADDR

#define BNO055_SIC_MATRIX_6_MSB_POS		(0)
#define BNO055_SIC_MATRIX_6_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_6_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_6_MSB_REG		BNO055_SIC_MATRIX_6_MSB_ADDR

#define BNO055_SIC_MATRIX_7_LSB_POS		(0)
#define BNO055_SIC_MATRIX_7_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_7_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_7_LSB_REG		BNO055_SIC_MATRIX_7_LSB_ADDR

#define BNO055_SIC_MATRIX_7_MSB_POS		(0)
#define BNO055_SIC_MATRIX_7_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_7_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_7_MSB_REG		BNO055_SIC_MATRIX_7_MSB_ADDR

#define BNO055_SIC_MATRIX_8_LSB_POS		(0)
#define BNO055_SIC_MATRIX_8_LSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_8_LSB_LEN		(8)
#define BNO055_SIC_MATRIX_8_LSB_REG		BNO055_SIC_MATRIX_8_LSB_ADDR

#define BNO055_SIC_MATRIX_8_MSB_POS		(0)
#define BNO055_SIC_MATRIX_8_MSB_MSK		(0XFF)
#define BNO055_SIC_MATRIX_8_MSB_LEN		(8)
#define BNO055_SIC_MATRIX_8_MSB_REG		BNO055_SIC_MATRIX_8_MSB_ADDR

/*Accel Offset registers*/
#define BNO055_ACCEL_OFFSET_X_LSB_POS		(0)
#define BNO055_ACCEL_OFFSET_X_LSB_MSK		(0XFF)
#define BNO055_ACCEL_OFFSET_X_LSB_LEN		(8)
#define BNO055_ACCEL_OFFSET_X_LSB_REG		BNO055_ACCEL_OFFSET_X_LSB_ADDR

#define BNO055_ACCEL_OFFSET_X_MSB_POS		(0)
#define BNO055_ACCEL_OFFSET_X_MSB_MSK		(0XFF)
#define BNO055_ACCEL_OFFSET_X_MSB_LEN		(8)
#define BNO055_ACCEL_OFFSET_X_MSB_REG		BNO055_ACCEL_OFFSET_X_MSB_ADDR

#define BNO055_ACCEL_OFFSET_Y_LSB_POS		(0)
#define BNO055_ACCEL_OFFSET_Y_LSB_MSK		(0XFF)
#define BNO055_ACCEL_OFFSET_Y_LSB_LEN		(8)
#define BNO055_ACCEL_OFFSET_Y_LSB_REG		BNO055_ACCEL_OFFSET_Y_LSB_ADDR

#define BNO055_ACCEL_OFFSET_Y_MSB_POS		(0)
#define BNO055_ACCEL_OFFSET_Y_MSB_MSK		(0XFF)
#define BNO055_ACCEL_OFFSET_Y_MSB_LEN		(8)
#define BNO055_ACCEL_OFFSET_Y_MSB_REG		BNO055_ACCEL_OFFSET_Y_MSB_ADDR

#define BNO055_ACCEL_OFFSET_Z_LSB_POS		(0)
#define BNO055_ACCEL_OFFSET_Z_LSB_MSK		(0XFF)
#define BNO055_ACCEL_OFFSET_Z_LSB_LEN		(8)
#define BNO055_ACCEL_OFFSET_Z_LSB_REG		BNO055_ACCEL_OFFSET_Z_LSB_ADDR

#define BNO055_ACCEL_OFFSET_Z_MSB_POS		(0)
#define BNO055_ACCEL_OFFSET_Z_MSB_MSK		(0XFF)
#define BNO055_ACCEL_OFFSET_Z_MSB_LEN		(8)
#define BNO055_ACCEL_OFFSET_Z_MSB_REG		BNO055_ACCEL_OFFSET_Z_MSB_ADDR

/*Mag Offset registers*/
#define BNO055_MAG_OFFSET_X_LSB_POS		(0)
#define BNO055_MAG_OFFSET_X_LSB_MSK		(0XFF)
#define BNO055_MAG_OFFSET_X_LSB_LEN		(8)
#define BNO055_MAG_OFFSET_X_LSB_REG		BNO055_MAG_OFFSET_X_LSB_ADDR

#define BNO055_MAG_OFFSET_X_MSB_POS		(0)
#define BNO055_MAG_OFFSET_X_MSB_MSK		(0XFF)
#define BNO055_MAG_OFFSET_X_MSB_LEN		(8)
#define BNO055_MAG_OFFSET_X_MSB_REG		BNO055_MAG_OFFSET_X_MSB_ADDR

#define BNO055_MAG_OFFSET_Y_LSB_POS		(0)
#define BNO055_MAG_OFFSET_Y_LSB_MSK		(0XFF)
#define BNO055_MAG_OFFSET_Y_LSB_LEN		(8)
#define BNO055_MAG_OFFSET_Y_LSB_REG		BNO055_MAG_OFFSET_Y_LSB_ADDR

#define BNO055_MAG_OFFSET_Y_MSB_POS		(0)
#define BNO055_MAG_OFFSET_Y_MSB_MSK		(0XFF)
#define BNO055_MAG_OFFSET_Y_MSB_LEN		(8)
#define BNO055_MAG_OFFSET_Y_MSB_REG		BNO055_MAG_OFFSET_Y_MSB_ADDR

#define BNO055_MAG_OFFSET_Z_LSB_POS		(0)
#define BNO055_MAG_OFFSET_Z_LSB_MSK		(0XFF)
#define BNO055_MAG_OFFSET_Z_LSB_LEN		(8)
#define BNO055_MAG_OFFSET_Z_LSB_REG		BNO055_MAG_OFFSET_Z_LSB_ADDR

#define BNO055_MAG_OFFSET_Z_MSB_POS		(0)
#define BNO055_MAG_OFFSET_Z_MSB_MSK		(0XFF)
#define BNO055_MAG_OFFSET_Z_MSB_LEN		(8)
#define BNO055_MAG_OFFSET_Z_MSB_REG		BNO055_MAG_OFFSET_Z_MSB_ADDR

/* Gyro Offset registers*/
#define BNO055_GYRO_OFFSET_X_LSB_POS		(0)
#define BNO055_GYRO_OFFSET_X_LSB_MSK		(0XFF)
#define BNO055_GYRO_OFFSET_X_LSB_LEN		(8)
#define BNO055_GYRO_OFFSET_X_LSB_REG		BNO055_GYRO_OFFSET_X_LSB_ADDR

#define BNO055_GYRO_OFFSET_X_MSB_POS		(0)
#define BNO055_GYRO_OFFSET_X_MSB_MSK		(0XFF)
#define BNO055_GYRO_OFFSET_X_MSB_LEN		(8)
#define BNO055_GYRO_OFFSET_X_MSB_REG		BNO055_GYRO_OFFSET_X_MSB_ADDR

#define BNO055_GYRO_OFFSET_Y_LSB_POS		(0)
#define BNO055_GYRO_OFFSET_Y_LSB_MSK		(0XFF)
#define BNO055_GYRO_OFFSET_Y_LSB_LEN		(8)
#define BNO055_GYRO_OFFSET_Y_LSB_REG		BNO055_GYRO_OFFSET_Y_LSB_ADDR

#define BNO055_GYRO_OFFSET_Y_MSB_POS		(0)
#define BNO055_GYRO_OFFSET_Y_MSB_MSK		(0XFF)
#define BNO055_GYRO_OFFSET_Y_MSB_LEN		(8)
#define BNO055_GYRO_OFFSET_Y_MSB_REG		BNO055_GYRO_OFFSET_Y_MSB_ADDR

#define BNO055_GYRO_OFFSET_Z_LSB_POS		(0)
#define BNO055_GYRO_OFFSET_Z_LSB_MSK		(0XFF)
#define BNO055_GYRO_OFFSET_Z_LSB_LEN		(8)
#define BNO055_GYRO_OFFSET_Z_LSB_REG		BNO055_GYRO_OFFSET_Z_LSB_ADDR

#define BNO055_GYRO_OFFSET_Z_MSB_POS		(0)
#define BNO055_GYRO_OFFSET_Z_MSB_MSK		(0XFF)
#define BNO055_GYRO_OFFSET_Z_MSB_LEN		(8)
#define BNO055_GYRO_OFFSET_Z_MSB_REG		BNO055_GYRO_OFFSET_Z_MSB_ADDR

/* Radius register definition*/
#define BNO055_ACCEL_RADIUS_LSB_POS		(0)
#define BNO055_ACCEL_RADIUS_LSB_MSK		(0XFF)
#define BNO055_ACCEL_RADIUS_LSB_LEN		(8)
#define BNO055_ACCEL_RADIUS_LSB_REG		BNO055_ACCEL_RADIUS_LSB_ADDR

#define BNO055_ACCEL_RADIUS_MSB_POS		(0)
#define BNO055_ACCEL_RADIUS_MSB_MSK		(0XFF)
#define BNO055_ACCEL_RADIUS_MSB_LEN		(8)
#define BNO055_ACCEL_RADIUS_MSB_REG		BNO055_ACCEL_RADIUS_MSB_ADDR

#define BNO055_MAG_RADIUS_LSB_POS		(0)
#define BNO055_MAG_RADIUS_LSB_MSK		(0XFF)
#define BNO055_MAG_RADIUS_LSB_LEN		(8)
#define BNO055_MAG_RADIUS_LSB_REG		BNO055_MAG_RADIUS_LSB_ADDR

#define BNO055_MAG_RADIUS_MSB_POS		(0)
#define BNO055_MAG_RADIUS_MSB_MSK		(0XFF)
#define BNO055_MAG_RADIUS_MSB_LEN		(8)
#define BNO055_MAG_RADIUS_MSB_REG		BNO055_MAG_RADIUS_MSB_ADDR

/* PAGE0 DATA REGISTERS DEFINITION END*/
/*************************************************/
/**\name PAGE1 DATA REGISTERS DEFINITION   */
/*************************************************/
/* Configuration registers*/
/* Accel range configuration register*/
#define BNO055_ACCEL_RANGE_POS		(0)
#define BNO055_ACCEL_RANGE_MSK		(0X03)
#define BNO055_ACCEL_RANGE_LEN		(2)
#define BNO055_ACCEL_RANGE_REG		BNO055_ACCEL_CONFIG_ADDR

/* Accel bandwidth configuration register*/
#define BNO055_ACCEL_BW_POS			(2)
#define BNO055_ACCEL_BW_MSK			(0X1C)
#define BNO055_ACCEL_BW_LEN			(3)
#define BNO055_ACCEL_BW_REG			BNO055_ACCEL_CONFIG_ADDR

/* Accel power mode configuration register*/
#define BNO055_ACCEL_POWER_MODE_POS		(5)
#define BNO055_ACCEL_POWER_MODE_MSK		(0XE0)
#define BNO055_ACCEL_POWER_MODE_LEN		(3)
#define BNO055_ACCEL_POWER_MODE_REG		BNO055_ACCEL_CONFIG_ADDR

/* Mag data output rate configuration register*/
#define BNO055_MAG_DATA_OUTPUT_RATE_POS		(0)
#define BNO055_MAG_DATA_OUTPUT_RATE_MSK		(0X07)
#define BNO055_MAG_DATA_OUTPUT_RATE_LEN		(3)
#define BNO055_MAG_DATA_OUTPUT_RATE_REG		BNO055_MAG_CONFIG_ADDR

/* Mag operation mode configuration register*/
#define BNO055_MAG_OPERATION_MODE_POS		(3)
#define BNO055_MAG_OPERATION_MODE_MSK		(0X18)
#define BNO055_MAG_OPERATION_MODE_LEN		(2)
#define BNO055_MAG_OPERATION_MODE_REG		BNO055_MAG_CONFIG_ADDR

/* Mag power mode configuration register*/
#define BNO055_MAG_POWER_MODE_POS		(5)
#define BNO055_MAG_POWER_MODE_MSK		(0X60)
#define BNO055_MAG_POWER_MODE_LEN		(2)
#define BNO055_MAG_POWER_MODE_REG		BNO055_MAG_CONFIG_ADDR

/* Gyro range configuration register*/
#define BNO055_GYRO_RANGE_POS		(0)
#define BNO055_GYRO_RANGE_MSK		(0X07)
#define BNO055_GYRO_RANGE_LEN		(3)
#define BNO055_GYRO_RANGE_REG		BNO055_GYRO_CONFIG_ADDR

/* Gyro bandwidth configuration register*/
#define BNO055_GYRO_BW_POS		(3)
#define BNO055_GYRO_BW_MSK		(0X38)
#define BNO055_GYRO_BW_LEN		(3)
#define BNO055_GYRO_BW_REG		BNO055_GYRO_CONFIG_ADDR

/* Gyro power mode configuration register*/
#define BNO055_GYRO_POWER_MODE_POS		(0)
#define BNO055_GYRO_POWER_MODE_MSK		(0X07)
#define BNO055_GYRO_POWER_MODE_LEN		(3)
#define BNO055_GYRO_POWER_MODE_REG		BNO055_GYRO_MODE_CONFIG_ADDR

/* Sleep configuration registers*/
/* Accel sleep mode configuration register*/
#define BNO055_ACCEL_SLEEP_MODE_POS		(0)
#define BNO055_ACCEL_SLEEP_MODE_MSK		(0X01)
#define BNO055_ACCEL_SLEEP_MODE_LEN		(1)
#define BNO055_ACCEL_SLEEP_MODE_REG		BNO055_ACCEL_SLEEP_CONFIG_ADDR

/* Accel sleep duration configuration register*/
#define BNO055_ACCEL_SLEEP_DURN_POS		(1)
#define BNO055_ACCEL_SLEEP_DURN_MSK		(0X1E)
#define BNO055_ACCEL_SLEEP_DURN_LEN		(4)
#define BNO055_ACCEL_SLEEP_DURN_REG		BNO055_ACCEL_SLEEP_CONFIG_ADDR

/* Gyro sleep duration configuration register*/
#define BNO055_GYRO_SLEEP_DURN_POS		(0)
#define BNO055_GYRO_SLEEP_DURN_MSK		(0X07)
#define BNO055_GYRO_SLEEP_DURN_LEN		(3)
#define BNO055_GYRO_SLEEP_DURN_REG		BNO055_GYRO_SLEEP_CONFIG_ADDR

/* Gyro auto sleep duration configuration register*/
#define BNO055_GYRO_AUTO_SLEEP_DURN_POS		(3)
#define BNO055_GYRO_AUTO_SLEEP_DURN_MSK		(0X38)
#define BNO055_GYRO_AUTO_SLEEP_DURN_LEN		(3)
#define BNO055_GYRO_AUTO_SLEEP_DURN_REG		BNO055_GYRO_SLEEP_CONFIG_ADDR

/* Mag sleep mode configuration register*/
#define BNO055_MAG_SLEEP_MODE_POS		(0)
#define BNO055_MAG_SLEEP_MODE_MSK		(0X01)
#define BNO055_MAG_SLEEP_MODE_LEN		(1)
#define BNO055_MAG_SLEEP_MODE_REG		BNO055_MAG_SLEEP_CONFIG_ADDR

/* Mag sleep duration configuration register*/
#define BNO055_MAG_SLEEP_DURN_POS		(1)
#define BNO055_MAG_SLEEP_DURN_MSK		(0X1E)
#define BNO055_MAG_SLEEP_DURN_LEN		(4)
#define BNO055_MAG_SLEEP_DURN_REG		BNO055_MAG_SLEEP_CONFIG_ADDR

/* Interrupt registers*/
/* Gyro any motion interrupt msk register*/
#define BNO055_GYRO_ANY_MOTION_INTR_MASK_POS		(2)
#define BNO055_GYRO_ANY_MOTION_INTR_MASK_MSK		(0X04)
#define BNO055_GYRO_ANY_MOTION_INTR_MASK_LEN		(1)
#define BNO055_GYRO_ANY_MOTION_INTR_MASK_REG		BNO055_INT_MASK_ADDR

/* Gyro high rate interrupt msk register*/
#define BNO055_GYRO_HIGHRATE_INTR_MASK_POS		(3)
#define BNO055_GYRO_HIGHRATE_INTR_MASK_MSK		(0X08)
#define BNO055_GYRO_HIGHRATE_INTR_MASK_LEN		(1)
#define BNO055_GYRO_HIGHRATE_INTR_MASK_REG		BNO055_INT_MASK_ADDR

/* Accel high g interrupt msk register*/
#define BNO055_ACCEL_HIGH_G_INTR_MASK_POS		(5)
#define BNO055_ACCEL_HIGH_G_INTR_MASK_MSK		(0X20)
#define BNO055_ACCEL_HIGH_G_INTR_MASK_LEN		(1)
#define BNO055_ACCEL_HIGH_G_INTR_MASK_REG		BNO055_INT_MASK_ADDR

/* Accel any motion interrupt msk register*/
#define BNO055_ACCEL_ANY_MOTION_INTR_MASK_POS		(6)
#define BNO055_ACCEL_ANY_MOTION_INTR_MASK_MSK		(0X40)
#define BNO055_ACCEL_ANY_MOTION_INTR_MASK_LEN		(1)
#define BNO055_ACCEL_ANY_MOTION_INTR_MASK_REG		BNO055_INT_MASK_ADDR

/* Accel any motion interrupt msk register*/
#define BNO055_ACCEL_NO_MOTION_INTR_MASK_POS		(7)
#define BNO055_ACCEL_NO_MOTION_INTR_MASK_MSK		(0X80)
#define BNO055_ACCEL_NO_MOTION_INTR_MASK_LEN		(1)
#define BNO055_ACCEL_NO_MOTION_INTR_MASK_REG		BNO055_INT_MASK_ADDR

/* Gyro any motion interrupt register*/
#define BNO055_GYRO_ANY_MOTION_INTR_POS		(2)
#define BNO055_GYRO_ANY_MOTION_INTR_MSK		(0X04)
#define BNO055_GYRO_ANY_MOTION_INTR_LEN		(1)
#define BNO055_GYRO_ANY_MOTION_INTR_REG		BNO055_INT_ADDR

/* Gyro high rate interrupt register*/
#define BNO055_GYRO_HIGHRATE_INTR_POS		(3)
#define BNO055_GYRO_HIGHRATE_INTR_MSK		(0X08)
#define BNO055_GYRO_HIGHRATE_INTR_LEN		(1)
#define BNO055_GYRO_HIGHRATE_INTR_REG		BNO055_INT_ADDR

/* Accel high g interrupt register*/
#define BNO055_ACCEL_HIGH_G_INTR_POS		(5)
#define BNO055_ACCEL_HIGH_G_INTR_MSK		(0X20)
#define BNO055_ACCEL_HIGH_G_INTR_LEN		(1)
#define BNO055_ACCEL_HIGH_G_INTR_REG		BNO055_INT_ADDR

/* Accel any motion interrupt register*/
#define BNO055_ACCEL_ANY_MOTION_INTR_POS		(6)
#define BNO055_ACCEL_ANY_MOTION_INTR_MSK		(0X40)
#define BNO055_ACCEL_ANY_MOTION_INTR_LEN		(1)
#define BNO055_ACCEL_ANY_MOTION_INTR_REG		BNO055_INT_ADDR

/*Accel any motion interrupt register*/
#define BNO055_ACCEL_NO_MOTION_INTR_POS		(7)
#define BNO055_ACCEL_NO_MOTION_INTR_MSK		(0X80)
#define BNO055_ACCEL_NO_MOTION_INTR_LEN		(1)
#define BNO055_ACCEL_NO_MOTION_INTR_REG		BNO055_INT_ADDR

/*Accel any motion threshold setting*/
#define BNO055_ACCEL_ANY_MOTION_THRES_POS	(0)
#define BNO055_ACCEL_ANY_MOTION_THRES_MSK	(0XFF)
#define BNO055_ACCEL_ANY_MOTION_THRES_LEN	(8)
#define BNO055_ACCEL_ANY_MOTION_THRES_REG  BNO055_ACCEL_ANY_MOTION_THRES_ADDR

/*Accel interrupt setting register*/
#define BNO055_ACCEL_ANY_MOTION_DURN_SET_POS		(0)
#define BNO055_ACCEL_ANY_MOTION_DURN_SET_MSK		(0X03)
#define BNO055_ACCEL_ANY_MOTION_DURN_SET_LEN		(2)
#define BNO055_ACCEL_ANY_MOTION_DURN_SET_REG  BNO055_ACCEL_INTR_SETTINGS_ADDR

/* Accel AM/NM axis selection register*/
#define BNO055_ACCEL_ANY_MOTION_X_AXIS_POS		(2)
#define BNO055_ACCEL_ANY_MOTION_X_AXIS_MSK		(0X04)
#define BNO055_ACCEL_ANY_MOTION_X_AXIS_LEN		(1)
#define BNO055_ACCEL_ANY_MOTION_X_AXIS_REG  BNO055_ACCEL_INTR_SETTINGS_ADDR

#define BNO055_ACCEL_ANY_MOTION_Y_AXIS_POS		(3)
#define BNO055_ACCEL_ANY_MOTION_Y_AXIS_MSK		(0X08)
#define BNO055_ACCEL_ANY_MOTION_Y_AXIS_LEN		(1)
#define BNO055_ACCEL_ANY_MOTION_Y_AXIS_REG  BNO055_ACCEL_INTR_SETTINGS_ADDR

#define BNO055_ACCEL_ANY_MOTION_Z_AXIS_POS		(4)
#define BNO055_ACCEL_ANY_MOTION_Z_AXIS_MSK		(0X10)
#define BNO055_ACCEL_ANY_MOTION_Z_AXIS_LEN		(1)
#define BNO055_ACCEL_ANY_MOTION_Z_AXIS_REG  BNO055_ACCEL_INTR_SETTINGS_ADDR

/* Accel high g axis selection register*/
#define BNO055_ACCEL_HIGH_G_X_AXIS_POS		(5)
#define BNO055_ACCEL_HIGH_G_X_AXIS_MSK		(0X20)
#define BNO055_ACCEL_HIGH_G_X_AXIS_LEN		(1)
#define BNO055_ACCEL_HIGH_G_X_AXIS_REG		BNO055_ACCEL_INTR_SETTINGS_ADDR

#define BNO055_ACCEL_HIGH_G_Y_AXIS_POS		(6)
#define BNO055_ACCEL_HIGH_G_Y_AXIS_MSK		(0X40)
#define BNO055_ACCEL_HIGH_G_Y_AXIS_LEN		(1)
#define BNO055_ACCEL_HIGH_G_Y_AXIS_REG		BNO055_ACCEL_INTR_SETTINGS_ADDR

#define BNO055_ACCEL_HIGH_G_Z_AXIS_POS		(7)
#define BNO055_ACCEL_HIGH_G_Z_AXIS_MSK		(0X80)
#define BNO055_ACCEL_HIGH_G_Z_AXIS_LEN		(1)
#define BNO055_ACCEL_HIGH_G_Z_AXIS_REG		BNO055_ACCEL_INTR_SETTINGS_ADDR

/* Accel High g duration setting register*/
#define BNO055_ACCEL_HIGH_G_DURN_POS		(0)
#define BNO055_ACCEL_HIGH_G_DURN_MSK		(0XFF)
#define BNO055_ACCEL_HIGH_G_DURN_LEN		(8)
#define BNO055_ACCEL_HIGH_G_DURN_REG		BNO055_ACCEL_HIGH_G_DURN_ADDR

/* Accel High g threshold setting register*/
#define BNO055_ACCEL_HIGH_G_THRES_POS		(0)
#define BNO055_ACCEL_HIGH_G_THRES_MSK		(0XFF)
#define BNO055_ACCEL_HIGH_G_THRES_LEN		(8)
#define BNO055_ACCEL_HIGH_G_THRES_REG		BNO055_ACCEL_HIGH_G_THRES_ADDR

/* Accel no/slow motion threshold setting*/
#define BNO055_ACCEL_SLOW_NO_MOTION_THRES_POS		(0)
#define BNO055_ACCEL_SLOW_NO_MOTION_THRES_MSK		(0XFF)
#define BNO055_ACCEL_SLOW_NO_MOTION_THRES_LEN		(8)
#define BNO055_ACCEL_SLOW_NO_MOTION_THRES_REG		\
BNO055_ACCEL_NO_MOTION_THRES_ADDR

/* Accel no/slow motion enable setting*/
#define BNO055_ACCEL_SLOW_NO_MOTION_ENABLE_POS		(0)
#define BNO055_ACCEL_SLOW_NO_MOTION_ENABLE_MSK		(0X01)
#define BNO055_ACCEL_SLOW_NO_MOTION_ENABLE_LEN		(1)
#define BNO055_ACCEL_SLOW_NO_MOTION_ENABLE_REG BNO055_ACCEL_NO_MOTION_SET_ADDR

/* Accel no/slow motion duration setting*/
#define BNO055_ACCEL_SLOW_NO_MOTION_DURN_POS		(1)
#define BNO055_ACCEL_SLOW_NO_MOTION_DURN_MSK		(0X7E)
#define BNO055_ACCEL_SLOW_NO_MOTION_DURN_LEN		(6)
#define BNO055_ACCEL_SLOW_NO_MOTION_DURN_REG   BNO055_ACCEL_NO_MOTION_SET_ADDR

/*Gyro interrupt setting register*/
/*Gyro any motion axis setting*/
#define BNO055_GYRO_ANY_MOTION_X_AXIS_POS		(0)
#define BNO055_GYRO_ANY_MOTION_X_AXIS_MSK		(0X01)
#define BNO055_GYRO_ANY_MOTION_X_AXIS_LEN		(1)
#define BNO055_GYRO_ANY_MOTION_X_AXIS_REG    BNO055_GYRO_INTR_SETING_ADDR

#define BNO055_GYRO_ANY_MOTION_Y_AXIS_POS		(1)
#define BNO055_GYRO_ANY_MOTION_Y_AXIS_MSK		(0X02)
#define BNO055_GYRO_ANY_MOTION_Y_AXIS_LEN		(1)
#define BNO055_GYRO_ANY_MOTION_Y_AXIS_REG    BNO055_GYRO_INTR_SETING_ADDR

#define BNO055_GYRO_ANY_MOTION_Z_AXIS_POS		(2)
#define BNO055_GYRO_ANY_MOTION_Z_AXIS_MSK		(0X04)
#define BNO055_GYRO_ANY_MOTION_Z_AXIS_LEN		(1)
#define BNO055_GYRO_ANY_MOTION_Z_AXIS_REG     BNO055_GYRO_INTR_SETING_ADDR

/*Gyro high rate axis setting*/
#define BNO055_GYRO_HIGHRATE_X_AXIS_POS		(3)
#define BNO055_GYRO_HIGHRATE_X_AXIS_MSK		(0X08)
#define BNO055_GYRO_HIGHRATE_X_AXIS_LEN		(1)
#define BNO055_GYRO_HIGHRATE_X_AXIS_REG		BNO055_GYRO_INTR_SETING_ADDR

#define BNO055_GYRO_HIGHRATE_Y_AXIS_POS		(4)
#define BNO055_GYRO_HIGHRATE_Y_AXIS_MSK		(0X10)
#define BNO055_GYRO_HIGHRATE_Y_AXIS_LEN		(1)
#define BNO055_GYRO_HIGHRATE_Y_AXIS_REG		BNO055_GYRO_INTR_SETING_ADDR

#define BNO055_GYRO_HIGHRATE_Z_AXIS_POS		(5)
#define BNO055_GYRO_HIGHRATE_Z_AXIS_MSK		(0X20)
#define BNO055_GYRO_HIGHRATE_Z_AXIS_LEN		(1)
#define BNO055_GYRO_HIGHRATE_Z_AXIS_REG		BNO055_GYRO_INTR_SETING_ADDR

/* Gyro filter setting*/
#define BNO055_GYRO_ANY_MOTION_FILTER_POS		(6)
#define BNO055_GYRO_ANY_MOTION_FILTER_MSK		(0X40)
#define BNO055_GYRO_ANY_MOTION_FILTER_LEN		(1)
#define BNO055_GYRO_ANY_MOTION_FILTER_REG    BNO055_GYRO_INTR_SETING_ADDR

#define BNO055_GYRO_HIGHRATE_FILTER_POS		(7)
#define BNO055_GYRO_HIGHRATE_FILTER_MSK		(0X80)
#define BNO055_GYRO_HIGHRATE_FILTER_LEN		(1)
#define BNO055_GYRO_HIGHRATE_FILTER_REG		BNO055_GYRO_INTR_SETING_ADDR

/* Gyro high rate X axis settings*/
#define BNO055_GYRO_HIGHRATE_X_THRES_POS		(0)
#define BNO055_GYRO_HIGHRATE_X_THRES_MSK		(0X1F)
#define BNO055_GYRO_HIGHRATE_X_THRES_LEN		(5)
#define BNO055_GYRO_HIGHRATE_X_THRES_REG    BNO055_GYRO_HIGHRATE_X_SET_ADDR

#define BNO055_GYRO_HIGHRATE_X_HYST_POS		(5)
#define BNO055_GYRO_HIGHRATE_X_HYST_MSK		(0X60)
#define BNO055_GYRO_HIGHRATE_X_HYST_LEN		(2)
#define BNO055_GYRO_HIGHRATE_X_HYST_REG		BNO055_GYRO_HIGHRATE_X_SET_ADDR

#define BNO055_GYRO_HIGHRATE_X_DURN_POS		(0)
#define BNO055_GYRO_HIGHRATE_X_DURN_MSK		(0XFF)
#define BNO055_GYRO_HIGHRATE_X_DURN_LEN		(8)
#define BNO055_GYRO_HIGHRATE_X_DURN_REG		BNO055_GYRO_DURN_X_ADDR

/* Gyro high rate Y axis settings*/
#define BNO055_GYRO_HIGHRATE_Y_THRES_POS		(0)
#define BNO055_GYRO_HIGHRATE_Y_THRES_MSK		(0X1F)
#define BNO055_GYRO_HIGHRATE_Y_THRES_LEN		(5)
#define BNO055_GYRO_HIGHRATE_Y_THRES_REG    BNO055_GYRO_HIGHRATE_Y_SET_ADDR

#define BNO055_GYRO_HIGHRATE_Y_HYST_POS		(5)
#define BNO055_GYRO_HIGHRATE_Y_HYST_MSK		(0X60)
#define BNO055_GYRO_HIGHRATE_Y_HYST_LEN		(2)
#define BNO055_GYRO_HIGHRATE_Y_HYST_REG		BNO055_GYRO_HIGHRATE_Y_SET_ADDR

#define BNO055_GYRO_HIGHRATE_Y_DURN_POS		(0)
#define BNO055_GYRO_HIGHRATE_Y_DURN_MSK		(0XFF)
#define BNO055_GYRO_HIGHRATE_Y_DURN_LEN		(8)
#define BNO055_GYRO_HIGHRATE_Y_DURN_REG		BNO055_GYRO_DURN_Y_ADDR

/* Gyro high rate Z axis settings*/
#define BNO055_GYRO_HIGHRATE_Z_THRES_POS		(0)
#define BNO055_GYRO_HIGHRATE_Z_THRES_MSK		(0X1F)
#define BNO055_GYRO_HIGHRATE_Z_THRES_LEN		(5)
#define BNO055_GYRO_HIGHRATE_Z_THRES_REG    BNO055_GYRO_HIGHRATE_Z_SET_ADDR

#define BNO055_GYRO_HIGHRATE_Z_HYST_POS		(5)
#define BNO055_GYRO_HIGHRATE_Z_HYST_MSK		(0X60)
#define BNO055_GYRO_HIGHRATE_Z_HYST_LEN		(2)
#define BNO055_GYRO_HIGHRATE_Z_HYST_REG		BNO055_GYRO_HIGHRATE_Z_SET_ADDR

#define BNO055_GYRO_HIGHRATE_Z_DURN_POS		(0)
#define BNO055_GYRO_HIGHRATE_Z_DURN_MSK		(0XFF)
#define BNO055_GYRO_HIGHRATE_Z_DURN_LEN		(8)
#define BNO055_GYRO_HIGHRATE_Z_DURN_REG		(BNO055_GYRO_DURN_Z_ADDR)

/*Gyro any motion threshold setting*/
#define BNO055_GYRO_ANY_MOTION_THRES_POS		(0)
#define BNO055_GYRO_ANY_MOTION_THRES_MSK		(0X7F)
#define BNO055_GYRO_ANY_MOTION_THRES_LEN		(7)
#define BNO055_GYRO_ANY_MOTION_THRES_REG		\
BNO055_GYRO_ANY_MOTION_THRES_ADDR

/* Gyro any motion slope sample setting*/
#define BNO055_GYRO_SLOPE_SAMPLES_POS		(0)
#define BNO055_GYRO_SLOPE_SAMPLES_MSK		(0X03)
#define BNO055_GYRO_SLOPE_SAMPLES_LEN		(2)
#define BNO055_GYRO_SLOPE_SAMPLES_REG		BNO055_GYRO_ANY_MOTION_SET_ADDR

/* Gyro awake duration setting*/
#define BNO055_GYRO_AWAKE_DURN_POS		(2)
#define BNO055_GYRO_AWAKE_DURN_MSK		(0X0C)
#define BNO055_GYRO_AWAKE_DURN_LEN		(2)
#define BNO055_GYRO_AWAKE_DURN_REG		BNO055_GYRO_ANY_MOTION_SET_ADDR
